<?php
$z[0]=Array("item","",4,94);
$z[0][4]['name']="更多织梦模板";
$z[0][4]['link']="http://www.dedecms.com";
$z[0][4]['rank']="";
$z[0][4]['target']="_blank";
$z[1]=Array("item","",98,196);
$z[1][4]['name']="意见建议反馈";
$z[1][4]['link']="http://site.desdev.cn/suggest/";
$z[1][4]['rank']="";
$z[1][4]['target']="_blank";
$z[2]=Array("item","",200,290);
$z[2][4]['name']="官方交流论坛";
$z[2][4]['link']="http://bbs.dedecms.com";
$z[2][4]['rank']="";
$z[2][4]['target']="_blank";

?>