<?php
$z[0]=Array("field","",320,339);
$z[0][4]['name']="title";
$z[1]=Array("global","",340,366);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",407,436);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",476,534);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3593,3631);
$z[4][4]['filename']="en_head.htm";
$z[5]=Array("field","",5500,5529);
$z[5][4]['name']="position";
$z[6]=Array("type","\r\n              <h2>[field:typename /]</h2>\r\n              ",5640,5722);
$z[7]=Array("field","",6280,6299);
$z[7][4]['name']="title";
$z[8]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a> ",6412,6488);
$z[9]=Array("field","",6542,6594);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("field","",6810,6828);
$z[10][4]['name']="body";
$z[11]=Array("include","",7130,7168);
$z[11][4]['filename']="en_left.htm";
$z[12]=Array("include","",7282,7322);
$z[12][4]['filename']="en_footer.htm";
$z[13]=Array("include","",7774,7815);
$z[13][4]['filename']="en_footer1.htm";

?>