<?php
$z[0]=Array("global","",1153,1179);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channelartlist","\r\n                                 <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>&nbsp; &nbsp; &nbsp;| &nbsp; &nbsp; \r\n                                 ",2137,2387);
$z[1][4]['typeid']="9,10,11,12,13,14,0";
$z[2]=Array("global","",3113,3141);
$z[2][4]['name']="cfg_powerbyen";
$z[3]=Array("global","",3165,3191);
$z[3][4]['name']="cfg_beianen";

?>