<?php
$z[0]=Array("global","\r\n                    \$a=\"\r\n                    <li class='col-5-1 last not-animated' data-animate='fadeInUp'>\";\r\n                      \$b=\"\r\n                    \r\n                    <li class='col-5-1 not-animated' data-animate='fadeInUp'>\";\r\n                      if ((@me%5)==0 && @me!=15)  @me=\$a;\r\n                      else  @me=\$b;\r\n                      ",0,420);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",532,547);
$z[2]=Array("picname","",575,591);
$z[3]=Array("title","",598,612);
$z[4]=Array("arcurl","",722,737);
$z[5]=Array("title","",755,769);

?>