<?php
$z[0]=Array("global","",1094,1120);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channelartlist"," <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>&nbsp; &nbsp; &nbsp;| &nbsp; &nbsp; \r\n                              ",1993,2201);
$z[1][4]['typeid']="2,3,4,5,6,7,0";
$z[2]=Array("global","",2849,2875);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",2899,2923);
$z[3][4]['name']="cfg_beian";

?>